# Generated by Django 5.1.2 on 2024-11-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='assistant_manager',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='attacking_coach',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='defending_coach',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='director_of_football',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='facilities_budget',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='team',
            name='goalkeeping_coach',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='merchandise',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='midfield_coach',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='physiotherapist',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='scout',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='set_piece_coach',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='stadium',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='training_facilties',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='transfer_budget',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='team',
            name='wage_budget',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='team',
            name='youth_academy',
            field=models.IntegerField(default=1),
        ),
    ]
