# Generated by Django 5.1.2 on 2024-11-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_team_assistant_manager_team_attacking_coach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='assistant_manager',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='attacking_coach',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='defending_coach',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='goalkeeping_coach',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='midfield_coach',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='physiotherapist',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='set_piece_coach',
            field=models.IntegerField(default=0),
        ),
    ]
