# Generated by Django 5.1.2 on 2024-11-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_scouted_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scouted_player',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
