# Generated by Django 5.1.2 on 2024-11-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_scouted_player_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scouted_player',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
