# Generated by Django 5.1.2 on 2024-11-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_scouted_player_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scouted_player',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
