# Generated by Django 5.1.2 on 2024-11-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_player_id_alter_scouted_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scouted_player',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
