# Generated by Django 5.1.2 on 2024-11-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='scout_reports_remaining',
            field=models.IntegerField(default=10),
        ),
    ]
