# Generated by Django 5.1.2 on 2024-11-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_team_scout_reports_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='scout_reports_used',
            field=models.IntegerField(default=0),
        ),
    ]
