# Generated by Django 5.1.2 on 2024-11-26 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_team_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_offered', to='management.player')),
                ('team_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_from', to='management.team')),
                ('team_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_to', to='management.team')),
            ],
        ),
    ]
