# Generated by Django 5.1.2 on 2024-11-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='accepted',
            field=models.BooleanField(default=None),
        ),
    ]
