# Generated by Django 5.1.2 on 2024-11-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_offer_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='accepted',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
