# Generated by Django 5.1.2 on 2024-11-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_alter_offer_accepted_alter_offer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='scout_reports_used',
        ),
        migrations.AddField(
            model_name='team',
            name='can_transfer',
            field=models.BooleanField(default=False),
        ),
    ]
