# Generated by Django 5.1.2 on 2024-12-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_remove_team_scout_reports_used_team_can_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='type',
            field=models.CharField(default='Transfer', max_length=10),
        ),
    ]
