# Generated by Django 5.1.2 on 2024-12-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_player_loaned_player_loaned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='loaned_wage',
            field=models.IntegerField(default=0),
        ),
    ]
