# Generated by Django 5.1.2 on 2024-12-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_player_loaned_wage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(default='default-logo.jpg', upload_to='team_logos'),
        ),
    ]
