# Generated by Django 5.1.2 on 2024-12-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(default='default-logo.png', upload_to='team_logos'),
        ),
    ]
