# Generated by Django 5.1.2 on 2024-12-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_alter_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='traits',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
