# Generated by Django 5.1.2 on 2024-12-27 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_player_traits'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='training_chance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='training_position',
            field=models.CharField(default='N/A', max_length=64),
        ),
        migrations.AddField(
            model_name='player',
            name='training_tactic',
            field=models.CharField(default='N/A', max_length=64),
        ),
        migrations.AddField(
            model_name='player',
            name='training_time',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(default='', max_length=10)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_notification', to='management.team')),
            ],
        ),
    ]
