# Generated by Django 5.1.2 on 2024-12-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_player_training_player_training_chance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='training_chance',
            new_name='training_position_chance',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='training_time',
            new_name='training_position_time',
        ),
        migrations.AddField(
            model_name='player',
            name='training_tactic_chance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='training_tactic_time',
            field=models.IntegerField(default=0),
        ),
    ]
