# Generated by Django 5.1.2 on 2024-12-29 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_rename_training_chance_player_training_position_chance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeder_Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='GFL Feeder Team', max_length=64)),
                ('level', models.IntegerField(default=40)),
                ('nation', models.CharField(default='England', max_length=64)),
                ('parent_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_club', to='management.team')),
            ],
        ),
    ]
