# Generated by Django 5.1.2 on 2024-12-29 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_feeder_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='feeder_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeder_players', to='management.feeder_team'),
        ),
    ]
