# Generated by Django 5.1.2 on 2024-12-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_player_feeder_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder_team',
            name='team_type',
            field=models.CharField(default='youth', max_length=64),
        ),
        migrations.AddField(
            model_name='player',
            name='sex',
            field=models.CharField(default='Male', max_length=64),
        ),
    ]
