# Generated by Django 5.1.5 on 2025-01-31 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_feeder_team_team_type_player_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='new_message',
            field=models.BooleanField(default=False),
        ),
    ]
