# Generated by Django 5.1.5 on 2025-01-31 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_team_new_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='new_message',
        ),
    ]
