# Generated by Django 5.1.5 on 2025-01-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_remove_team_new_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='new_message',
            field=models.BooleanField(default=False),
        ),
    ]
