# Generated by Django 5.1.5 on 2025-03-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_team_new_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='out_of_league_loan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scouted_player',
            name='can_be_loaned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scouted_player',
            name='loaned_wage',
            field=models.IntegerField(default=0),
        ),
    ]
