# Generated by Django 5.1.5 on 2025-03-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_player_out_of_league_loan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scouted_player',
            name='loaned',
            field=models.BooleanField(default=False),
        ),
    ]
