# Generated by Django 5.1.5 on 2025-05-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_scouted_player_loaned'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='free_agent',
            field=models.BooleanField(default=False),
        ),
    ]
