# Generated by Django 5.1.5 on 2025-05-02 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_player_free_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dribbling',
            field=models.CharField(default='Balanced', max_length=64),
        ),
        migrations.AddField(
            model_name='player',
            name='duty',
            field=models.CharField(default='Support', max_length=64),
        ),
        migrations.AddField(
            model_name='player',
            name='freedom',
            field=models.CharField(default='Balanced', max_length=64),
        ),
        migrations.AddField(
            model_name='player',
            name='lineup_position',
            field=models.CharField(default='N/A', max_length=64),
        ),
        migrations.AddField(
            model_name='player',
            name='risk_taking',
            field=models.CharField(default='Balanced', max_length=64),
        ),
        migrations.AddField(
            model_name='player',
            name='shooting',
            field=models.CharField(default='Balanced', max_length=64),
        ),
        migrations.AddField(
            model_name='player',
            name='tackling',
            field=models.CharField(default='Balanced', max_length=64),
        ),
        migrations.AddField(
            model_name='team',
            name='formation',
            field=models.CharField(default='4-4-2', max_length=64),
        ),
        migrations.AddField(
            model_name='team',
            name='mentality',
            field=models.CharField(default='Balanced', max_length=64),
        ),
        migrations.AddField(
            model_name='team',
            name='tactic',
            field=models.CharField(default='Balanced', max_length=64),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='lineup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='management.player')),
                ('player_10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_10', to='management.player')),
                ('player_11', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_11', to='management.player')),
                ('player_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to='management.player')),
                ('player_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_3', to='management.player')),
                ('player_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_4', to='management.player')),
                ('player_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_5', to='management.player')),
                ('player_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_6', to='management.player')),
                ('player_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_7', to='management.player')),
                ('player_8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_8', to='management.player')),
                ('player_9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_9', to='management.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_lineup', to='management.team')),
            ],
        ),
    ]
