# Generated by Django 5.1.5 on 2025-05-05 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_player_dribbling_player_duty_player_freedom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='player_12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_12', to='management.player'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='player_13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_13', to='management.player'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='player_14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_14', to='management.player'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='player_15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_15', to='management.player'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='player_16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_16', to='management.player'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='player_17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_17', to='management.player'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='player_18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_18', to='management.player'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='player_19',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_19', to='management.player'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='player_20',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_20', to='management.player'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='player_21',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_21', to='management.player'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='player_22',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_22', to='management.player'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='player_23',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_23', to='management.player'),
        ),
    ]
