# Generated by Django 5.1.5 on 2025-05-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_lineup_player_12_lineup_player_13_lineup_player_14_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='overall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='lineup_rating',
            field=models.IntegerField(default=0),
        ),
    ]
