# Generated by Django 5.1.5 on 2025-01-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='new_message',
            field=models.BooleanField(default=False),
        ),
    ]
