# Generated by Django 5.1.5 on 2025-01-31 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_new_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='new_message',
        ),
    ]
